// Generated by CoffeeScript 1.8.0
(function() {
  var debug, log;

  debug = require('debug')("app:test");

  log = require('../lib/log')(debug);

  console.log(debug);

  debug.error("123");

}).call(this);

//# sourceMappingURL=test_log.js.map
