// Generated by CoffeeScript 1.8.0
(function() {
  var email, errorLog, fs;

  fs = require('fs');

  email = require('./email')();

  errorLog = fs.createWriteStream('../logs/error.log', {
    flags: 'a'
  });

  module.exports = function(debug) {
    return debug.error = function(body) {
      var write;
      if (body == null) {
        body = '';
      }
      debug.color = 1;
      debug(body);
      debug.color = 6;
      body = String(body);
      write = {
        time: new Date(),
        errInfo: body
      };
      body = JSON.stringify(write);
      errorLog.write(body + '\n');
      return email.send(body);
    };
  };

}).call(this);

//# sourceMappingURL=log.js.map
